#!/usr/bin/env python3
"""Generate playfield bytes for the SQUEEPTY title and scrolling ticker."""

TITLE_FONT = {
    "S": ("1111", "1000", "1000", "1111", "0001", "0001", "1111"),
    "Q": ("1110", "1001", "1001", "1001", "1011", "1110", "0011"),
    "U": ("1001", "1001", "1001", "1001", "1001", "1001", "1111"),
    "E": ("1111", "1000", "1000", "1110", "1000", "1000", "1111"),
    "P": ("1110", "1001", "1001", "1110", "1000", "1000", "1000"),
    "T": ("1111", "0110", "0110", "0110", "0110", "0110", "0110"),
    "Y": ("1001", "1001", "1001", "0110", "0110", "0110", "0110"),
}

TICKER_FONT = {
    " ": ("000", "000", "000", "000", "000"),
    "/": ("001", "001", "010", "100", "100"),
    "0": ("111", "101", "101", "101", "111"),
    "2": ("110", "001", "010", "100", "111"),
    "6": ("011", "100", "111", "101", "111"),
    "A": ("010", "101", "111", "101", "101"),
    "D": ("110", "101", "101", "101", "110"),
    "E": ("111", "100", "110", "100", "111"),
    "F": ("111", "100", "110", "100", "100"),
    "H": ("101", "101", "111", "101", "101"),
    "L": ("100", "100", "100", "100", "111"),
    "M": ("101", "111", "111", "101", "101"),
    "O": ("111", "101", "101", "101", "111"),
    "P": ("110", "101", "110", "100", "100"),
    "Q": ("111", "101", "101", "111", "001"),
    "R": ("110", "101", "110", "101", "101"),
    "S": ("011", "100", "111", "001", "110"),
    "T": ("111", "010", "010", "010", "010"),
    "U": ("101", "101", "101", "101", "111"),
    "Y": ("101", "101", "010", "010", "010"),
}


def text_rows(text, font, height, spacing=1):
    rows = [[] for _ in range(height)]
    for char_index, char in enumerate(text):
        glyph = font[char]
        for row_index, row in enumerate(glyph):
            rows[row_index].extend(int(pixel) for pixel in row)
            if spacing and char_index != len(text) - 1:
                rows[row_index].extend([0] * spacing)
    return rows


def reverse_bits(value):
    result = 0
    for bit in range(8):
        result |= ((value >> bit) & 1) << (7 - bit)
    return result


def bits_to_byte(bits):
    value = 0
    for bit in bits:
        value = (value << 1) | bit
    return value


def encode_half(pixels):
    """Encode 20 left-to-right pixels as PF0/PF1/PF2 register values."""
    pf0 = sum(pixel << (4 + index) for index, pixel in enumerate(pixels[:4]))
    pf1 = bits_to_byte(pixels[4:12])
    pf2 = reverse_bits(bits_to_byte(pixels[12:20]))
    return pf0, pf1, pf2


def encode_row(pixels):
    padded = (pixels + [0] * 40)[:40]
    left = encode_half(padded[:20])
    right = encode_half(padded[20:40])
    return left + right


def emit_bytes(label, values, per_line=16):
    print(f"{label}")
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        encoded = ",".join(f"${value:02X}" for value in chunk)
        print(f"    byte {encoded}")


def generate_title():
    rows = text_rows("SQUEEPTY", TITLE_FONT, 7)
    rows = [[0] * 1 + row for row in rows]
    encoded = [encode_row(row) for row in rows]
    labels = (
        "TitlePF0L",
        "TitlePF1L",
        "TitlePF2L",
        "TitlePF0R",
        "TitlePF1R",
        "TitlePF2R",
    )
    for column, label in enumerate(labels):
        emit_bytes(label, [row[column] for row in encoded])


def generate_scroll():
    message = "   HELLO FROM SQUEEPTY / 2600 DEMO   "
    source_rows = text_rows(message, TICKER_FONT, 5)
    width = len(source_rows[0])
    offsets = range(0, width, 2)
    frames = []

    # Two-pixel steps are smooth enough for this compact first-demo kernel.
    for offset in offsets:
        frame_rows = []
        for source in source_rows:
            wrapped = source + source
            window = wrapped[offset : offset + 40]
            frame_rows.append(encode_row(window))

        # Buffer layout is register-major so the kernel can index by text row.
        for register in range(6):
            frames.extend(row[register] for row in frame_rows)

    emit_bytes("ScrollFrames", frames)
    print("ScrollFramesEnd")
    print(f"SCROLL_FRAME_COUNT = {len(offsets)}")


print("; Generated by tools/gen_assets.py. Do not edit by hand.")
generate_title()
generate_scroll()
